### PR TITLE
fix: feedback system / close #64

### LINKED ISSUE #64: Support PP FeedBack System
Hallo Wie auf Discord Besprochen schreibe ich dir hier noch mal das Problem

das Feedback System macht einen Eintrag in der Datenbank, nur wird das Ergebnis was der User als Zahl eingibt nicht in der Datenbank gespeichert.

Script Version 2.6.2
Sinusbot Version: 1.0.0-beta.10-202ee4d

Meine Log
2020-07-06T14:52:01+02:00 [ support-pp:2897:32] [MySQL] Insert new Question to DB.
2020-07-06T14:52:01+02:00 [ support-pp:2881:20] 0=0
2020-07-06T14:51:47+02:00 [ support-pp:3716:24] Support++ | ChannelEdit
2020-07-06T14:51:47+02:00 [ support-pp:3716:24] Support++ | ChannelEdit

Edit @Jniklas2 : Hab die Sinusbot Version, welche auf Discord geschrieben wurde, übernommen, sowie die Rechtschreibfehler verbessert ;)

### PR DESCRIPTION
**Pull request by VerHext**
fix: feedback system  #64

### CODE REVIEW

**Comment by VerHext** [comment]
Waiting for testing results in #64

**Comment by Lapotor** [comment]
Is it fixed or still work in progress?

**Comment by VerHext** [comment]
@Lapotor this wp is a fix and should solve the memory problems of the feedback module. The "WIP" only set to block a direct push into the main branch. As soon as I get test results from #64, I will remove this.

**Comment by VerHext** [comment]
I write the changelog blog post already for this release: https://medium.com/support-pp/2-6-3-783b564d89b3

**Pull request merged**
